# -*- coding: utf-8 -*-
"""data_exploration

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pcA4IT7Ouxu5s_9LDa4UYwz1916AxHb5
"""

# Step 1: Data Exploration
def data_exploration():
    print("Step 1: Data Exploration")
    #Target variable: weather_code (since it indicates different weather condition
    df = pd.read_csv("hourly_weather.csv")
    # Display basic information about the dataset
    print(df.info())
    # Display the first few rows of the dataset
    print(df.head())

data_exploration()