# -*- coding: utf-8 -*-
"""model_training

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pcA4IT7Ouxu5s_9LDa4UYwz1916AxHb5
"""

# Step 6: Model Training
def model_training():
    print("Step 6: Model Training")
    # Fit and transform the imputer on the training data
    X_train_imputed = imputer.fit_transform(X_train)
    # Transform the test data using the trained imputer
    X_test_imputed = imputer.transform(X_test)
    # Train the Random Forest Classifier on the imputed training data
    rf_model.fit(X_train_imputed, y_train)
    # Predict on the imputed test data
    y_pred_imputed = rf_model.predict(X_test_imputed)