# -*- coding: utf-8 -*-
"""import_libraries

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pcA4IT7Ouxu5s_9LDa4UYwz1916AxHb5
"""

# Import necessary libraries
from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python_operator import PythonOperator
import pandas as pd